name: Build/run tgov

on:
  push:
    branches: [ "main", "deploy-lambda" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: "1.3.2"
      POETRY_VENV: "/opt/poetry-venv"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        python3 -m venv "${POETRY_VENV}"
        $POETRY_VENV/bin/pip install -U pip setuptools
        $POETRY_VENV/bin/pip install "poetry==${POETRY_VERSION}"
        "PATH=${PATH}:${POETRY_VENV}/bin" >> $env:GITHUB_ENV
        poetry config virtualenvs.create false
        poetry install
    - name: Run Diarization
      run: |
        python src/run_diarization.py
