name: Update Meetings Summary

on:
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder workflow to allow testing on the new branch."
